import type { Metadata } from "next";

// Templates
import Header from "../templates/header";
import Footer from "../templates/footer";

// Styles
import "../styles/style.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="header-hold">
          <Header />
        </div>
        <div className="content-hold">
          {children}
        </div>
        <div className="footer-hold">
          <Footer />
        </div>
      </body>
    </html>
  );
}
